receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  file/traces:
    path: /output/traces.jsonl
  file/metrics:
    path: /output/metrics.jsonl
  file/logs:
    path: /output/logs.jsonl

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file/traces]
    metrics:
      receivers: [otlp]
      exporters: [file/metrics]
    logs:
      receivers: [otlp]
      exporters: [file/logs]
